"""Initial Migration

Revision ID: 965181070d0e
Revises: 7fd3a4fa9d6c
Create Date: 2019-09-20 16:31:54.876126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965181070d0e'
down_revision = '7fd3a4fa9d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
